import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import WelcomeSection from '../src/components/Welcome/WelcomeSection';
import CategoryCard from '../src/components/Cards/CategoryCard';
import Grid from '@mui/material/Grid';
import Tools from '../src/components/Tools';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <WelcomeSection authUserName={"MD. Hamjjah"} /> */}
      {/* <Box >
        <Tools />
      </Box> */}
      <Box sx={{ flexGrow: 1 }}>
        <Grid container spacing={{ xs: 2, md: 3 }} columns={{ xs: 4, sm: 8, md: 12, lg: 16 }}>
          {Array.from(Array(12)).map((_, index) => (
            <Grid item xs={4} sm={4} md={4} key={index}>
              <CategoryCard />
            </Grid> 
          ))}
        </Grid>
      </Box>


    </div>
  )
}

export default Home
